// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mid_Project.Data;

#nullable disable

namespace Mid_Project.Migrations
{
    [DbContext(typeof(SystemDbContext))]
    partial class SystemDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BussTrip", b =>
                {
                    b.Property<int>("bussbus_Id")
                        .HasColumnType("int");

                    b.Property<int>("trip_Id")
                        .HasColumnType("int");

                    b.HasKey("bussbus_Id", "trip_Id");

                    b.HasIndex("trip_Id");

                    b.ToTable("BussTrip");
                });

            modelBuilder.Entity("Mid_Project.Models.Admin", b =>
                {
                    b.Property<int>("admin_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("admin_Id"), 1L, 1);

                    b.Property<string>("full_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("admin_Id");

                    b.ToTable("admin");
                });

            modelBuilder.Entity("Mid_Project.Models.Buss", b =>
                {
                    b.Property<int>("bus_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("bus_Id"), 1L, 1);

                    b.Property<int>("AdminID")
                        .HasColumnType("int");

                    b.Property<string>("captin_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("number_of_seats")
                        .HasColumnType("int");

                    b.HasKey("bus_Id");

                    b.HasIndex("AdminID");

                    b.ToTable("buss");
                });

            modelBuilder.Entity("Mid_Project.Models.Passenger", b =>
                {
                    b.Property<int>("pass_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("pass_Id"), 1L, 1);

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("phone")
                        .HasColumnType("int");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("pass_Id");

                    b.ToTable("passenger");
                });

            modelBuilder.Entity("Mid_Project.Models.Trip", b =>
                {
                    b.Property<int>("trip_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("trip_Id"), 1L, 1);

                    b.Property<int>("AdminID")
                        .HasColumnType("int");

                    b.Property<int>("bus_Number")
                        .HasColumnType("int");

                    b.Property<string>("destination")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("end_Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("start_Date")
                        .HasColumnType("datetime2");

                    b.HasKey("trip_Id");

                    b.HasIndex("AdminID");

                    b.ToTable("trip");
                });

            modelBuilder.Entity("PassengerTrip", b =>
                {
                    b.Property<int>("passengerpass_Id")
                        .HasColumnType("int");

                    b.Property<int>("trip_Id")
                        .HasColumnType("int");

                    b.HasKey("passengerpass_Id", "trip_Id");

                    b.HasIndex("trip_Id");

                    b.ToTable("PassengerTrip");
                });

            modelBuilder.Entity("BussTrip", b =>
                {
                    b.HasOne("Mid_Project.Models.Buss", null)
                        .WithMany()
                        .HasForeignKey("bussbus_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mid_Project.Models.Trip", null)
                        .WithMany()
                        .HasForeignKey("trip_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mid_Project.Models.Buss", b =>
                {
                    b.HasOne("Mid_Project.Models.Admin", "admin")
                        .WithMany("buss")
                        .HasForeignKey("AdminID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("admin");
                });

            modelBuilder.Entity("Mid_Project.Models.Trip", b =>
                {
                    b.HasOne("Mid_Project.Models.Admin", "Admin")
                        .WithMany("trip")
                        .HasForeignKey("AdminID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("PassengerTrip", b =>
                {
                    b.HasOne("Mid_Project.Models.Passenger", null)
                        .WithMany()
                        .HasForeignKey("passengerpass_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mid_Project.Models.Trip", null)
                        .WithMany()
                        .HasForeignKey("trip_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mid_Project.Models.Admin", b =>
                {
                    b.Navigation("buss");

                    b.Navigation("trip");
                });
#pragma warning restore 612, 618
        }
    }
}
